name: dive_computer
description: "A Flutter plugin for communication with dive computers."
version: 0.1.0-dev.1
homepage: "https://divenote.app"
repository: "https://github.com/DiveNote/dive_computer"
issue_tracker: "https://github.com/DiveNote/dive_computer/issues"
funding: 
 - "https://github.com/sponsors/Sese-Schneider"

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  ffi: '>=2.1.0 <3.0.0'
  flutter:
    sdk: flutter
  logging: '>=1.2.0 <2.0.0'
  path: '>=1.8.0 <2.0.0'
  plugin_platform_interface: '>=2.0.2 <3.0.0'
  flutter_blue_plus: ^1.31.15

dev_dependencies:
  ffigen: ">=10.0.0 <12.0.0"
  flutter_test:
    sdk: flutter
  flutter_lints: ">=2.0.0 <4.0.0"

flutter:
  plugin:
    platforms:
      windows:
        ffiPlugin: true
      android:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      ios:
        ffiPlugin: true
        